function [fitresult, gof] = createFit_two(xData, yData, w_fixed)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'test' fit:
%      X Input: x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Jun-2022 10:03:28


%% Fit: 'test'.

% Set up fittype and options.
ft = fittype('fourier2');

opts = fitoptions('Method', 'NonlinearLeastSquares' );
opts.DiffMaxChange = 1;
opts.Display = 'Off';
opts.MaxFunEvals = 800;
opts.MaxIter = 600;
opts.Robust = 'Bisquare';
opts.StartPoint = [0 0 0 0 0 w_fixed];%1.25663706143592
opts.Lower = [-Inf -Inf -Inf -Inf -Inf w_fixed];
opts.Upper = [Inf Inf Inf Inf Inf w_fixed];

% Fit model to data.
[fitresult, gof] = fit(xData, yData, ft, opts);

end


